# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@2
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure for Students (8fd70241-1e7c-431a-91b1-be11c2bbe677)'
    backendAzureRmResourceGroupName: 'CyberResponse-backend'
    backendAzureRmStorageAccountName: 'cyberresponse07'
    backendAzureRmContainerName: 'irptfcontainer'
    backendAzureRmKey: 'terraform.tfstate'