name: Deploy app CI CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
    NODE_VERSION: '18.x'                # set this to the node version to use

permissions:
    contents: read
    id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: testdeploy
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@v4
        
    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: 'npm install, build, and test'
      run: |
        npm install
        NODE_OPTIONS=--openssl-legacy-provider npm run build

    - name: 'Azure CLI Login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    # deploy web app using Azure credentials
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: reportcr
        package: ./build
